platform :ios, '10.0'
use_frameworks!

target 'TheMovieDB' do

  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireImage', '~> 3.3'
  pod 'OHHTTPStubs/Swift'

  target 'TheMovieDBTests' do
    inherit! :search_paths
  end
end
